config/routes.rb
APSSueldos::Application.routes.draw do |map|

  resources :companies

  resources :consortia

  resources :numeradors

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  resources :users

  resources :sicoss_format_employers

  resources :sicoss_formats

  resources :sicoss_regimen_types

  resources :sicoss_reduction_zones

  resources :sicoss_locations

  resources :sicoss_damageds

  resources :sicoss_contract_modes

  resources :sicoss_activities

  resources :sicoss_conditions

  resources :sicoss_situations

  resources :sicoss_employer_types

  resources :siscoss_regimen_types

  resources :siscoss_regimen

  resources :siscoss_reduction_zones

  resources :siscoss_locations

  resources :siscoss_contract_modes

  resources :siscoss_activities

  resources :siscoss_conditions

  resources :siscoss_situations

  resources :siscoss_employer_types

  resources :syscoss_regimen_types

  resources :syscoss_regimen

  resources :syscoss_reduction_zones

  resources :syscoss_locations

  resources :syscoss_damageds

  resources :syscoss_contract_modes

  resources :syscoss_activities

  resources :syscoss_conditions

  resources :syscoss_situations

  resources :syscoss_employer_types

  resources :employer_types

  resources :activities

  resources :kinships

  resources :associated_document_types

  resources :EmployeeDocumentsController

  map.resources :attachments    , :only => :show

  resources :causa_egresos

  resources :email_types

  resources :employees do
    resources :employee_familiars
    resources :employee_retention_concepts
    resources :employee_remunerative_concepts
  end
  resources :deduccion_ganancias_tables

  resources :tipo_recibos

  resources :categories do
    member do
      get "imprimir", :action => :print
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  match '/print_table' => 'application#print_table', :via => :get
  match 'liquidacions/control_by_company_list' => 'liquidacions#control_by_company_list', :via => :get
  resources :liquidacions do
    member do
       get "control_by_company", :action => :control_by_company
    end
    resources :recibo_sueldos do
      member do
        get "control_by_company", :action => :control_by_company
        get "update_approved_fields", :action => :update_approved_fields
        get "update_disapproved_fields", :action => :update_disapproved_fields
      end
      resources :detalle_recibo_retencions
      resources :detalle_recibo_habers
      member do
        get "calculo_recibo", :action => :calculo_recibo
      end
    end
  end

  resources :data_to_asks

  resources :group_remunerations

  resources :employer_contribution_concepts

  resources :retention_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :remunerative_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :activities, :path => 'Actividades'

  resources :insurance_beneficiaries

  resources :bank_deposits

  resources :educational_levels

  resources :group_employer_contributions

  resources :bank_deposit_account_types

  resources :insurance_companies

  resources :employments

  resources :accounting_imputations

  resources :contract_modes

  resources :home_abouts

  resources :cost_centers

  resources :group_retentions

  resources :remuneration_types

  resources :labor_unions

  resources :health_insurances

  resources :places

  resources :tasks

  resources :sections

  resources :character_services

  resources :countries

  resources :provinces

  resources :locations

  resources :marital_statuses

  resources :nationalities

  resources :issueds

  resources :document_types

  resources :menus
  resources :menu_roles
  resources :menu_users
  resources :user_authorizations
  resources :user_roles

  root :to => "liquidacions#index"
  

end

app/models/employee_remunerative_concept.rb
# == Schema Information
# Schema version: 20110721162735
#
# Table name: employee_remunerative_concepts
#
#  id                      :integer         not null, primary key
#  employee_id             :integer
#  remunerative_concept_id :integer
#  cantidad                :integer
#  importe                 :float
#  fecha_inicio            :date
#  fecha_final             :date
#  created_at              :datetime
#  updated_at              :datetime
#  cost_center_id          :integer
#  detalle                 :text
#

require 'custom_validators'

class EmployeeRemunerativeConcept < ActiveRecord::Base
  belongs_to :employee
  belongs_to :remunerative_concept
  belongs_to :cost_center

  validates_presence_of		    :remunerative_concept_id ,															:message => "es un dato requerido"
  validates_numericality_of   :cantidad, :if => :cantidad?
  validates_numericality_of   :importe, :allow_blank => true

#  validates_with RemunerativeConceptsDataToAskValidator, :campos => [:cantidad, :importe], :if => :remunerative_concept_id?
end

app/controllers/employee_remunerative_concepts_controller.rb
class EmployeeRemunerativeConceptsController < ApplicationController
  before_filter :find_employee

  # GET /employee_remunerative_concepts
  # GET /employee_remunerative_concepts.xml
  def index
    @employee_remunerative_concepts = @employee.employee_remunerative_concept.all

    respond_to do |format|
      format.html # indexoo.html.erb
      format.xml  { render :xml => @employee_remunerative_concepts }
    end
  end

  # GET /employee_remunerative_concepts/1
  # GET /employee_remunerative_concepts/1.xml
  def show
    @employee_remunerative_concept = @employee.employee_remunerative_concept.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee_remunerative_concept }
    end
  end

  # GET /employee_remunerative_concepts/new
  # GET /employee_remunerative_concepts/new.xml
  def new
    @employee_remunerative_concept = @employee.employee_remunerative_concept.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @employee_remunerative_concept }
    end
  end

  # GET /employee_remunerative_concepts/1/edit
  def edit
    @employee_remunerative_concept = @employee.employee_remunerative_concept.find(params[:id])
  end

  # POST /employee_remunerative_concepts
  # POST /employee_remunerative_concepts.xml
  def create
    @employee_remunerative_concept = @employee.employee_remunerative_concept.build(params[@employee,:employee_remunerative_concept])

    respond_to do |format|
      if @employee_remunerative_concept.save
        format.html { redirect_to([@employee, @employee_remunerative_concept], :notice => 'Employee remunerative concept was successfully created.') }
        format.xml  { render :xml => @employee_remunerative_concept, :status => :created, :location => @employee_remunerative_concept }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @employee_remunerative_concept.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employee_remunerative_concepts/1
  # PUT /employee_remunerative_concepts/1.xml
  def update
    @employee_remunerative_concept = @employee.employee_emunerative_concept.find(params[:id])

    respond_to do |format|
      if @employee_remunerative_concept.update_attributes(params[:employee_remunerative_concept])
        format.html { redirect_to([@employee,@employee_remunerative_concept], :notice => 'Employee remunerative concept was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee_remunerative_concept.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_remunerative_concepts/1
  # DELETE /employee_remunerative_concepts/1.xml
  def destroy
    @employee_remunerative_concept = @employee.employee_remunerative_concept.find(params[:id])
    @employee_remunerative_concept.destroy

    respond_to do |format|
      format.html { redirect_to(employee_remunerative_concepts_url) }
      format.xml  { head :ok }
    end
  end

  protected
  def find_employee
    raise "Debe Ingresar con un empleado!!!!!!!!!!!" if params[:employee_id].blank?
    @employee = Employee.find(params[:employee_id])
  end

end

app/helpers/employee_remunerative_concepts_helper.rb
module EmployeeRemunerativeConceptsHelper
end

app/views/employee_remunerative_concepts/_form.html.haml
= form_for(@employee_remunerative_concept) do |f|
  = render 'shared/errorhandler', :obj_errors => @employee_remunerative_concept.errors
  .clear
  .form_box
    .form_box_title
    /  %span.title= EmployeeRemunerativeConcept.model_name.human
    %table.tableForm
      %tr
        %td.columnLabel
          = f.label :employee_id, :class => "apsLabel"
        %td.columnData
          = f.text_field :employee_id, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :remunerative_concept_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :remunerative_concept_id, RemunerativeConcept.all, :id, :detalle, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :cantidad, :class => "apsLabel"
        %td.columnData
          = f.text_field :cantidad, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :importe, :class => "apsLabel"
        %td.columnData
          = f.text_field :importe, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :fecha_inicio, :class => "apsLabel"
        %td.columnData
          = f.text_field :fecha_inicio, :value => @employee_remunerative_concept.fecha_inicio.to_s, :class => "apsDatetime"
      %tr
        %td.columnLabel
          = f.label :fecha_final, :class => "apsLabel"
        %td.columnData
          = f.text_field :fecha_final, :value => @employee_remunerative_concept.fecha_final.to_s, :class => "apsDatetime"
      %tr
        %td.columnLabel
          = f.label :cost_center_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :cost_center_id, CostCenter.all, :id, :detalle, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :detalle, :class => "apsLabel"
        %td.columnData
          = f.text_field :detalle, :class => "apsTextbox"
  .actions
    = f.submit :class => "btn success"

app/views/employee_remunerative_concepts/edit.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeRemunerativeConcept.model_name.human, employee_remunerative_concepts_path 
    - breadcrumb.item "#{@employee_remunerative_concept.detalle.titlecase}", employee_remunerative_concept_path(@employee_remunerative_concept), :active => true

= link_to t('scaffold.actions.show').titlecase, employee_remunerative_concept_path(@employee_remunerative_concept), :class => "btn info" 
.clear
%br/
= render 'form'

app/views/employee_remunerative_concepts/index.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeRemunerativeConcept.model_name.human, employee_remunerative_concepts_path, :active => true
.clear
- if true
  = link_to t('scaffold.actions.new', :item => EmployeeRemunerativeConcept.model_name.human) , new_employee_remunerative_concept_path(@employee_remunerative_concept), :class => "btn success" 
  - if @employee_remunerative_concepts.any?
    = link_to t('scaffold.actions.export').titlecase, "/print_table?tablename=" + EmployeeRemunerativeConcept.model_name, :class => "btn info"

- if @employee_remunerative_concepts.any?
  %table.tableStandard
    %tr
      %th= sort_link @search, :employee_id, @employee_remunerative_concepts.human_attribute_name('employee_id')
      %th= sort_link @search, :remunerative_concept_id, @employee_remunerative_concepts.human_attribute_name('remunerative_concept_id')
      %th= sort_link @search, :cantidad, @employee_remunerative_concepts.human_attribute_name('cantidad')
      %th= sort_link @search, :importe, @employee_remunerative_concepts.human_attribute_name('importe')
      %th= sort_link @search, :fecha_inicio, @employee_remunerative_concepts.human_attribute_name('fecha_inicio')
      %th= sort_link @search, :fecha_final, @employee_remunerative_concepts.human_attribute_name('fecha_final')
      %th= sort_link @search, :cost_center_id, @employee_remunerative_concepts.human_attribute_name('cost_center_id')
      %th= sort_link @search, :detalle, @employee_remunerative_concepts.human_attribute_name('detalle')
      %th.last

    - @employee_remunerative_concepts.each do |item|
      %tr
        %td= item.employee_id
        %td= item.remunerative_concept_id
        %td= item.cantidad
        %td= item.importe
        %td= item.fecha_inicio
        %td= item.fecha_final
        %td= item.cost_center_id
        %td= item.detalle
        %td.last.actions
          = link_to icon('application_get', :small, :title => t('scaffold.actions.show').titlecase), item, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_edit', :small, :title => t('scaffold.actions.edit').titlecase), edit_employee_remunerative_concept_path(item), :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_delete', :small, :title => t('scaffold.actions.destroy').titlecase), item, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
    .clear
    .block{:style => 'margin:20px;'}= paginate(@employee_remunerative_concepts)
  .clear
.clear

app/views/employee_remunerative_concepts/new.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeRemunerativeConcept.model_name.human, employee_remunerative_concepts_path
    - breadcrumb.item t('scaffold.actions.new', :item => EmployeeRemunerativeConcept.model_name.human).titlecase , nil, :active => true

= render 'form'

app/views/employee_remunerative_concepts/show.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeRemunerativeConcept.model_name.human, employee_remunerative_concepts_path 
    - breadcrumb.item "#{@employee_remunerative_concept.detalle.titlecase}", nil, :active => true

= link_to t('scaffold.actions.edit').titlecase, edit_employee_remunerative_concept_path(@employee_remunerative_concept), :class => "btn success" |
= link_to t('scaffold.actions.destroy').titlecase, @employee_remunerative_concept, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :class => "btn danger"
.clear
%br/
= form_for(@employee_remunerative_concept) do |f|
  = render 'shared/errorhandler', :obj_errors => @employee_remunerative_concept.errors
  .form_box
    %table.tableForm
      %tr
        %td.columnLabel
          = f.label :employee_id, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.employee_id
      %tr
        %td.columnLabel
          = f.label :remunerative_concept_id, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.remunerative_concept.try(:detalle)
      %tr
        %td.columnLabel
          = f.label :cantidad, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.cantidad
      %tr
        %td.columnLabel
          = f.label :importe, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.importe
      %tr
        %td.columnLabel
          = f.label :fecha_inicio, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.fecha_inicio
      %tr
        %td.columnLabel
          = f.label :fecha_final, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.fecha_final
      %tr
        %td.columnLabel
          = f.label :cost_center_id, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.cost_center.try(:detalle)
      %tr
        %td.columnLabel
          = f.label :detalle, :class => "apsLabel"
        %td.columnData
          = @employee_remunerative_concept.detalle
.clear