config/routes.rb
APSSueldos::Application.routes.draw do |map|

  resources :companies

  resources :consortia

  resources :numeradors

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  resources :users

  resources :sicoss_format_employers

  resources :sicoss_formats

  resources :sicoss_regimen_types

  resources :sicoss_reduction_zones

  resources :sicoss_locations

  resources :sicoss_damageds

  resources :sicoss_contract_modes

  resources :sicoss_activities

  resources :sicoss_conditions

  resources :sicoss_situations

  resources :sicoss_employer_types

  resources :siscoss_regimen_types

  resources :siscoss_regimen

  resources :siscoss_reduction_zones

  resources :siscoss_locations

  resources :siscoss_contract_modes

  resources :siscoss_activities

  resources :siscoss_conditions

  resources :siscoss_situations

  resources :siscoss_employer_types

  resources :syscoss_regimen_types

  resources :syscoss_regimen

  resources :syscoss_reduction_zones

  resources :syscoss_locations

  resources :syscoss_damageds

  resources :syscoss_contract_modes

  resources :syscoss_activities

  resources :syscoss_conditions

  resources :syscoss_situations

  resources :syscoss_employer_types

  resources :employer_types

  resources :activities

  resources :kinships

  resources :associated_document_types

  resources :EmployeeDocumentsController

  map.resources :attachments    , :only => :show

  resources :causa_egresos

  resources :email_types

  resources :employees do
    resources :employee_familiars
    resources :employee_retention_concepts
    resources :employee_remunerative_concepts
  end
  resources :deduccion_ganancias_tables

  resources :tipo_recibos

  resources :categories do
    member do
      get "imprimir", :action => :print
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  match '/print_table' => 'application#print_table', :via => :get
  match 'liquidacions/control_by_company_list' => 'liquidacions#control_by_company_list', :via => :get
  resources :liquidacions do
    member do
       get "control_by_company", :action => :control_by_company
    end
    resources :recibo_sueldos do
      member do
        get "control_by_company", :action => :control_by_company
        get "update_approved_fields", :action => :update_approved_fields
        get "update_disapproved_fields", :action => :update_disapproved_fields
      end
      resources :detalle_recibo_retencions
      resources :detalle_recibo_habers
      member do
        get "calculo_recibo", :action => :calculo_recibo
      end
    end
  end

  resources :data_to_asks

  resources :group_remunerations

  resources :employer_contribution_concepts

  resources :retention_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :remunerative_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :activities, :path => 'Actividades'

  resources :insurance_beneficiaries

  resources :bank_deposits

  resources :educational_levels

  resources :group_employer_contributions

  resources :bank_deposit_account_types

  resources :insurance_companies

  resources :employments

  resources :accounting_imputations

  resources :contract_modes

  resources :home_abouts

  resources :cost_centers

  resources :group_retentions

  resources :remuneration_types

  resources :labor_unions

  resources :health_insurances

  resources :places

  resources :tasks

  resources :sections

  resources :character_services

  resources :countries

  resources :provinces

  resources :locations

  resources :marital_statuses

  resources :nationalities

  resources :issueds

  resources :document_types

  resources :menus
  resources :menu_roles
  resources :menu_users
  resources :user_authorizations
  resources :user_roles

  root :to => "liquidacions#index"
  

end

app/models/employee_familiar.rb
# == Schema Information
# Schema version: 20111013184648
#
# Table name: employee_familiars
#
#  id                  :integer         not null, primary key
#  apellido            :string(255)
#  nombre              :string(255)
#  fecha_nacimiento    :date
#  numero_documento    :integer
#  health_insurance_id :integer
#  cuil                :string(255)
#  cuit                :string(255)
#  tomo                :string(255)
#  folio               :string(255)
#  acta                :string(255)
#  country_id          :integer
#  province_id         :integer
#  comuna              :string(255)
#  employee_id         :integer
#  document_type_id    :integer
#  activity_id         :integer
#  created_at          :datetime
#  updated_at          :datetime
#  kinship_id          :integer
#  address             :string(255)
#  porcentual          :string(255)
#

class EmployeeFamiliar < ActiveRecord::Base
	belongs_to :employee
	belongs_to :activity
	belongs_to :document_type
  belongs_to :health_insurance
  belongs_to :country
  belongs_to :province
  belongs_to :kinship




	validates_presence_of		  :nombre,															                      :message => "es un dato requerido"
	validates_presence_of		  :apellido,									                						    :message => "es un dato requerido"
	validates_presence_of		  :numero_documento,                													:message => "es un dato requerido"
  validates_presence_of		  :fecha_nacimiento,						                							:message => "es un dato requerido"

  validates_numericality_of :numero_documento, :greater_than_or_equal_to => 0,					:message => "acepta valores positivos"

end

app/controllers/employee_familiars_controller.rb
class EmployeeFamiliarsController < ApplicationController
  before_filter :find_employee

  def index
    @employee_familiars = @employee.employee_familiar.all

    respond_to do |format|
      format.html # index.html.erbb
      format.xml  { render :xml => @employee_familiars }
    end
  end

  def show
    @employee_familiar = @employee.employee_familiar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee_familiar }
    end
  end

  def new
    @employee_familiar = @employee.employee_familiar.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @employee_familiar }
    end
  end

  def edit
    @employee_familiar = @employee.employee_familiar.find(params[:id])
  end

  def create
    @employee_familiar = @employee.employee_familiar.build(params[@employee, :employee_familiar])

    respond_to do |format|
      if @employee_familiar.save
        format.html { redirect_to([@employee, @employee_familiar], :notice => 'Employee familiar was successfully created.') }
        format.xml  { render :xml => @employee_familiar, :status => :created, :location => @employee_familiar }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @employee_familiar.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @employee_familiar = @employee.employee_familiar.find(params[:id])

    respond_to do |format|
      if @employee_familiar.update_attributes(params[:employee_familiar])
        format.html { redirect_to(@employee_familiar, :notice => 'Employee familiar was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee_familiar.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee_familiar = @employee.employee_familiar.find(params[:id])
    @employee_familiar.destroy

    respond_to do |format|
      format.html { redirect_to(employee_familiars_url) }
      format.xml  { head :ok }
    end
  end

  protected
  def find_employee
    raise "Debe Ingresar con un empleado!!!!!!!!!!!" if params[:employee_id].blank?
    @employee = Employee.find(params[:employee_id])
  end

end

app/helpers/employee_familiars_helper.rb
module EmployeeFamiliarsHelper
end

app/views/employee_familiars/_form.html.haml
= form_for(@employee_familiar) do |f|
  = render 'shared/errorhandler', :obj_errors => @employee_familiar.errors
  .clear
  .form_box
    .form_box_title
    /  %span.title= EmployeeFamiliar.model_name.human
    %table.tableForm
      %tr
        %td.columnLabel
          = f.label :apellido, :class => "apsLabel"
        %td.columnData
          = f.text_field :apellido, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :nombre, :class => "apsLabel"
        %td.columnData
          = f.text_field :nombre, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :fecha_nacimiento, :class => "apsLabel"
        %td.columnData
          = f.text_field :fecha_nacimiento, :value => @employee_familiar.fecha_nacimiento.to_s, :class => "apsDatetime"
      %tr
        %td.columnLabel
          = f.label :numero_documento, :class => "apsLabel"
        %td.columnData
          = f.text_field :numero_documento, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :health_insurance_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :health_insurance_id, HealthInsurance.all, :id, :detalle, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :cuil, :class => "apsLabel"
        %td.columnData
          = f.text_field :cuil, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :cuit, :class => "apsLabel"
        %td.columnData
          = f.text_field :cuit, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :tomo, :class => "apsLabel"
        %td.columnData
          = f.text_field :tomo, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :folio, :class => "apsLabel"
        %td.columnData
          = f.text_field :folio, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :acta, :class => "apsLabel"
        %td.columnData
          = f.text_field :acta, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :country_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :country_id, Country.all, :id, :detalle, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :province_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :province_id, Province.all, :id, :detalle, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :comuna, :class => "apsLabel"
        %td.columnData
          = f.text_field :comuna, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :employee_id, :class => "apsLabel"
        %td.columnData
          = f.text_field :employee_id, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :document_type_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :document_type_id, DocumentType.all, :id, :detalle, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :activity_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :activity_id, Activity.all, :id, :name, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :kinship_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :kinship_id, Kinship.all, :id, :name, {:class => "apsSelect"}, {:include_blank => 'Sin datos'}
      %tr
        %td.columnLabel
          = f.label :address, :class => "apsLabel"
        %td.columnData
          = f.text_field :address, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :porcentual, :class => "apsLabel"
        %td.columnData
          = f.text_field :porcentual, :class => "apsTextbox"
  .actions
    = f.submit :class => "btn success"

app/views/employee_familiars/edit.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeFamiliar.model_name.human, employee_familiars_path , :active => true

= link_to t('scaffold.actions.show').titlecase, employee_familiar_path(@employee_familiar), :class => "btn info" 
.clear
%br/
= render 'form'

app/views/employee_familiars/index.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeFamiliar.model_name.human, employee_familiars_path, :active => true
.clear
- if true
  = link_to t('scaffold.actions.new', :item => EmployeeFamiliar.model_name.human) , new_employee_familiar_path(@employee_familiar), :class => "btn success" 
  - if @employee_familiars.any?
    = link_to t('scaffold.actions.export').titlecase, "/print_table?tablename=" + EmployeeFamiliar.model_name, :class => "btn info"

- if @employee_familiars.any?
  %table.tableStandard
    %tr
      %th= sort_link @search, :apellido, @employee_familiars.human_attribute_name('apellido')
      %th= sort_link @search, :nombre, @employee_familiars.human_attribute_name('nombre')
      %th= sort_link @search, :fecha_nacimiento, @employee_familiars.human_attribute_name('fecha_nacimiento')
      %th= sort_link @search, :numero_documento, @employee_familiars.human_attribute_name('numero_documento')
      %th= sort_link @search, :health_insurance_id, @employee_familiars.human_attribute_name('health_insurance_id')
      %th= sort_link @search, :cuil, @employee_familiars.human_attribute_name('cuil')
      %th= sort_link @search, :cuit, @employee_familiars.human_attribute_name('cuit')
      %th= sort_link @search, :tomo, @employee_familiars.human_attribute_name('tomo')
      %th= sort_link @search, :folio, @employee_familiars.human_attribute_name('folio')
      %th= sort_link @search, :acta, @employee_familiars.human_attribute_name('acta')
      %th= sort_link @search, :country_id, @employee_familiars.human_attribute_name('country_id')
      %th= sort_link @search, :province_id, @employee_familiars.human_attribute_name('province_id')
      %th= sort_link @search, :comuna, @employee_familiars.human_attribute_name('comuna')
      %th= sort_link @search, :employee_id, @employee_familiars.human_attribute_name('employee_id')
      %th= sort_link @search, :document_type_id, @employee_familiars.human_attribute_name('document_type_id')
      %th= sort_link @search, :activity_id, @employee_familiars.human_attribute_name('activity_id')
      %th= sort_link @search, :kinship_id, @employee_familiars.human_attribute_name('kinship_id')
      %th= sort_link @search, :address, @employee_familiars.human_attribute_name('address')
      %th= sort_link @search, :porcentual, @employee_familiars.human_attribute_name('porcentual')
      %th.last

    - @employee_familiars.each do |item|
      %tr
        %td= item.apellido
        %td= item.nombre
        %td= item.fecha_nacimiento
        %td= item.numero_documento
        %td= item.health_insurance_id
        %td= item.cuil
        %td= item.cuit
        %td= item.tomo
        %td= item.folio
        %td= item.acta
        %td= item.country_id
        %td= item.province_id
        %td= item.comuna
        %td= item.employee_id
        %td= item.document_type_id
        %td= item.activity_id
        %td= item.kinship_id
        %td= item.address
        %td= item.porcentual
        %td.last.actions
          = link_to icon('application_get', :small, :title => t('scaffold.actions.show').titlecase), item, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_edit', :small, :title => t('scaffold.actions.edit').titlecase), edit_employee_familiar_path(item), :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_delete', :small, :title => t('scaffold.actions.destroy').titlecase), item, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
    .clear
    .block{:style => 'margin:20px;'}= paginate(@employee_familiars)
  .clear
.clear

app/views/employee_familiars/new.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeFamiliar.model_name.human, employee_familiars_path
    - breadcrumb.item t('scaffold.actions.new', :item => EmployeeFamiliar.model_name.human).titlecase , nil, :active => true

= render 'form'

app/views/employee_familiars/show.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item EmployeeFamiliar.model_name.human, employee_familiars_path , :active => true

= link_to t('scaffold.actions.edit').titlecase, edit_employee_familiar_path(@employee_familiar), :class => "btn success" |
= link_to t('scaffold.actions.destroy').titlecase, @employee_familiar, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :class => "btn danger"
.clear
%br/
= form_for(@employee_familiar) do |f|
  = render 'shared/errorhandler', :obj_errors => @employee_familiar.errors
  .form_box
    %table.tableForm
      %tr
        %td.columnLabel
          = f.label :apellido, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.apellido
      %tr
        %td.columnLabel
          = f.label :nombre, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.nombre
      %tr
        %td.columnLabel
          = f.label :fecha_nacimiento, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.fecha_nacimiento
      %tr
        %td.columnLabel
          = f.label :numero_documento, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.numero_documento
      %tr
        %td.columnLabel
          = f.label :health_insurance_id, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.health_insurance.try(:detalle)
      %tr
        %td.columnLabel
          = f.label :cuil, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.cuil
      %tr
        %td.columnLabel
          = f.label :cuit, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.cuit
      %tr
        %td.columnLabel
          = f.label :tomo, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.tomo
      %tr
        %td.columnLabel
          = f.label :folio, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.folio
      %tr
        %td.columnLabel
          = f.label :acta, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.acta
      %tr
        %td.columnLabel
          = f.label :country_id, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.country.try(:detalle)
      %tr
        %td.columnLabel
          = f.label :province_id, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.province.try(:detalle)
      %tr
        %td.columnLabel
          = f.label :comuna, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.comuna
      %tr
        %td.columnLabel
          = f.label :employee_id, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.employee_id
      %tr
        %td.columnLabel
          = f.label :document_type_id, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.document_type.try(:detalle)
      %tr
        %td.columnLabel
          = f.label :activity_id, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.activity.try(:name)
      %tr
        %td.columnLabel
          = f.label :kinship_id, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.kinship.try(:name)
      %tr
        %td.columnLabel
          = f.label :address, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.address
      %tr
        %td.columnLabel
          = f.label :porcentual, :class => "apsLabel"
        %td.columnData
          = @employee_familiar.porcentual
.clear