config/routes.rb
APSSueldos::Application.routes.draw do |map|

  resources :companies

  resources :consortia

  resources :numeradors

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  resources :users

  resources :sicoss_format_employers

  resources :sicoss_formats

  resources :sicoss_regimen_types

  resources :sicoss_reduction_zones

  resources :sicoss_locations

  resources :sicoss_damageds

  resources :sicoss_contract_modes

  resources :sicoss_activities

  resources :sicoss_conditions

  resources :sicoss_situations

  resources :sicoss_employer_types

  resources :siscoss_regimen_types

  resources :siscoss_regimen

  resources :siscoss_reduction_zones

  resources :siscoss_locations

  resources :siscoss_contract_modes

  resources :siscoss_activities

  resources :siscoss_conditions

  resources :siscoss_situations

  resources :siscoss_employer_types

  resources :syscoss_regimen_types

  resources :syscoss_regimen

  resources :syscoss_reduction_zones

  resources :syscoss_locations

  resources :syscoss_damageds

  resources :syscoss_contract_modes

  resources :syscoss_activities

  resources :syscoss_conditions

  resources :syscoss_situations

  resources :syscoss_employer_types

  resources :employer_types

  resources :activities

  resources :kinships

  resources :associated_document_types

  resources :EmployeeDocumentsController

  map.resources :attachments    , :only => :show

  resources :causa_egresos

  resources :email_types

  resources :employees do
    resources :employee_familiars
    resources :employee_retention_concepts
    resources :employee_remunerative_concepts
  end
  resources :deduccion_ganancias_tables

  resources :tipo_recibos

  resources :categories do
    member do
      get "imprimir", :action => :print
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  match '/print_table' => 'application#print_table', :via => :get
  match 'liquidacions/control_by_company_list' => 'liquidacions#control_by_company_list', :via => :get
  resources :liquidacions do
    member do
       get "control_by_company", :action => :control_by_company
    end
    resources :recibo_sueldos do
      member do
        get "control_by_company", :action => :control_by_company
        get "update_approved_fields", :action => :update_approved_fields
        get "update_disapproved_fields", :action => :update_disapproved_fields
      end
      resources :detalle_recibo_retencions
      resources :detalle_recibo_habers
      member do
        get "calculo_recibo", :action => :calculo_recibo
      end
    end
  end

  resources :data_to_asks

  resources :group_remunerations

  resources :employer_contribution_concepts

  resources :retention_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :remunerative_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :activities, :path => 'Actividades'

  resources :insurance_beneficiaries

  resources :bank_deposits

  resources :educational_levels

  resources :group_employer_contributions

  resources :bank_deposit_account_types

  resources :insurance_companies

  resources :employments

  resources :accounting_imputations

  resources :contract_modes

  resources :home_abouts

  resources :cost_centers

  resources :group_retentions

  resources :remuneration_types

  resources :labor_unions

  resources :health_insurances

  resources :places

  resources :tasks

  resources :sections

  resources :character_services

  resources :countries

  resources :provinces

  resources :locations

  resources :marital_statuses

  resources :nationalities

  resources :issueds

  resources :document_types

  resources :menus
  resources :menu_roles
  resources :menu_users
  resources :user_authorizations
  resources :user_roles

  root :to => "liquidacions#index"
  

end

app/models/liquidacion.rb
# == Schema Information
# Schema version: 20110721162735
#
# Table name: liquidacions
#
#  id                :integer         not null, primary key
#  fecha_liquidacion :date
#  fecha_deposito    :date
#  bank_deposit_id   :integer
#  fecha_cierre      :date
#  quincena          :integer
#  techo_retenciones :decimal(, )
#  created_at        :datetime
#  updated_at        :datetime
#  tipo_recibo_id    :integer
#  periodo           :date
#  periodo_deposito  :date
#  company_id        :integer
#

class Liquidacion < ActiveRecord::Base
  scope :by_company, lambda {|company| where(:company_id => company) }
  #default_scope where(:company_id => current_company.id)

  has_many :recibo_sueldos, :dependent => :restrict
  belongs_to :tipo_recibo
  belongs_to :bank_deposit

  validates_uniqueness_of     :periodo,
                              :scope => [:quincena, :tipo_recibo_id,:company_id],:message => "+quincena+tipo recibo duplicado"
  validates_inclusion_of 	    :quincena, :in => 1..2,                           :message => "valores posibles 1 o 2"

	validates_presence_of		    :periodo, :quincena,
                              :fecha_liquidacion, :bank_deposit_id, 					  :message => "es un dato requerido"
  validates_presence_of		    :fecha_deposito,
                              :if => :periodo_deposito?,		    			          :message => "es un dato requerido"

  default_scope order('periodo ASC')

#  validate                    :check_periodo
  def retrieve_all_employee_with_recibo_sueldos
      liquidados = []
      recibo_sueldos.each do |r|
        liquidados << r.employee
      end
      return liquidados
  end
  def retrieve_all_employee_without_recibo_sueldos(current_company_id)
    Employee.by_company(current_company_id).all.reject { |n| self.retrieve_all_employee_with_recibo_sueldos.include?(n) }
#    Employee.where(:id => current_company_id).all.reject { |n| self.retrieve_all_employee_with_recibo_sueldos.include?(n) }
  end

  private
#  def check_periodo
#    if :periodo[0..3].to_i > 2010
#       errors.add(:periodo, "el Ano debe ser mayor a 2011")
#    end
##    if (1..12).include?(periodo[-2..-1].to_i)
#    unless (1..12).include?(periodo[5..6].to_i)
#       errors.add(:periodo, "el Mes debe estar comprendido entre 01 y 12")
#    end
#    if :periodo[0..3].to_i > 2010
#       errors.add(:periodo_deposito, 'el Ano del debe ser mayor a 2011')
#    end
#    unless (1..12).include?(periodo[-2..-1].to_i)
#       errors.add(:periodo_deposito, "el Mes debe estar comprendido entre 01 y 12")
#    end
#  end

  def full_period
#    apellido + ', '+nombre
   [(periodo.ano.to_s +'/'+ periodo_mes.to_s), quincena].compact.join(' Quincena ')
  end

end

app/controllers/liquidacions_controller.rb
class LiquidacionsController < ApplicationController
  before_filter :find_liquidacion, :except => [:index, :new, :create, :control_by_company_list]

  # GET /liquidacions
  # GET /liquidacions.xml
  def index
    @search = Liquidacion.by_company(current_company.id).search(params[:search])
    @liquidacions = @search.page(params[:page]).per(10)

    respond_to do |format|
      format.html # indexoo.html.erb
      format.xml  { render :xml => @liquidacions }
#      format.text do
#        render :text => @liquidacions.first.periodo
#      end
    end
  end

  # GET /liquidacions/1
  # GET /liquidacions/1.xml
  def show

    respond_to do |format|
      format.html # show.html.erb
#      format.xml  { render :xml => @liquidacion }
      format.xml  do
        print_table('RemunerativeConcept')
      end

      format.pdf do
        dump_tmp_filename = Rails.root.join('tmp',@liquidacion.cache_key)
          Dir.mkdir(dump_tmp_filename.dirname) unless File.directory?(dump_tmp_filename.dirname)
          if print_libro_pdf(dump_tmp_filename,@liquidacion)
            send_file(dump_tmp_filename, :type => :pdf, :disposition => 'attachment', :filename => "librosueldos.pdf")
            File.delete(dump_tmp_filename) unless Rails.env.development?
          else
            redirect_to :action => 'show'
          end
      end

      format.json do
        dump_tmp_filename = Rails.root.join('tmp',@liquidacion.cache_key)
          Dir.mkdir(dump_tmp_filename.dirname) unless File.directory?(dump_tmp_filename.dirname)
          print_planilla_remuneraciones_pdf(dump_tmp_filename,@liquidacion)
          send_file(dump_tmp_filename, :type => :pdf, :disposition => 'attachment', :filename => "planilla_remuneraciones.pdf")
          File.delete(dump_tmp_filename) unless Rails.env.development?
      end

      format.text  do
        dump_tmp_filename = Rails.root.join('tmp',@liquidacion.cache_key)
        Dir.mkdir(dump_tmp_filename.dirname) unless File.directory?(dump_tmp_filename.dirname)
        prepara_sicoss(dump_tmp_filename,@liquidacion)
        send_file(dump_tmp_filename, :type => :text, :disposition => 'attachment', :filename => "sicoss_interfase.txt")
        File.delete(dump_tmp_filename) unless Rails.env.development?
      end
    end
  end

  # GET /liquidacions/new
  # GET /liquidacions/new.xml
  def new
    @liquidacion = Liquidacion.by_company(current_company.id).new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @liquidacion }
    end
  end

  # GET /liquidacions/1/edit
  def edit
  end

  # POST /liquidacions
  # POST /liquidacions.xml
  def create
    @liquidacion = Liquidacion.by_company(current_company.id).new(params[:liquidacion])

    respond_to do |format|
      if @liquidacion.save
        liquidar_employee

        format.html { redirect_to(@liquidacion, :notice => t('scaffold.notice.created', :item=> Liquidacion.model_name.human)) }
        format.xml  { render :xml => @liquidacion, :status => :created, :location => @liquidacion }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @liquidacion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /liquidacions/1
  # PUT /liquidacions/1.xml
  def update

    respond_to do |format|
      if @liquidacion.update_attributes(params[:liquidacion])
        format.html { redirect_to(@liquidacion, :notice => t('scaffold.notice.updated', :item=> Liquidacion.model_name.human)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @liquidacion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /liquidacions/1
  # DELETE /liquidacions/1.xml
  def destroy
    begin
      @liquidacion.destroy
      flash[:success] = "successfully destroyed."
    rescue ActiveRecord::DeleteRestrictionError => e
      @liquidacion.errors.add(:base, e)
      flash[:error] = "#{e}"
      redirect_to liquidacion_url
    else
      redirect_to liquidacions_url
    end
  end

  #[PVD] :: 2011-10-26 :: Listado de control de recibos de sueldo para MDQ...
  def control_by_company_list
    @liquidacions = Liquidacion.by_company(current_company.id).order("periodo desc")
    respond_to do |format|
      format.html {}
      format.xml  { head :ok }
      format.json {}
    end
  end

  #[PVD] :: 2011-10-26 :: Listado de los recibos de sueldo de una liquidacion
  def control_by_company
    respond_to do |format|
      format.html {}
      format.xml  { head :ok }
      format.json {}
    end
  end

  protected

  def find_liquidacion
      @liquidacion= Liquidacion.by_company(current_company.id).find(params[:id])
  end

  def liquidar_employee
    @employees = Employee.by_company(current_company.id).where(:fecha_egreso.blank?)
    Rails.logger.info("Cant="+@employees.count.to_s)

    @employees.each do |employee|
      Rails.logger.info("Employee="+employee.id.to_s)
      @recibo_sueldo = ReciboSueldo.new(:liquidacion_id => @liquidacion.id, :employee_id => employee.id)
      @recibo_sueldo.save
      @recibo_sueldo.calcular_recibo
    end
  end

# #################################################################################
  def print_planilla_remuneraciones_pdf(filename,liquidacion_actual)
  require 'prawn'

  empresa = OpenStruct.new({
                  :logo                   => "",
                  :empresa                => "",
                  :domicilio              => "",
                  :cuit                   => "",
                  :inscripcion            => "",
                  :caja                   => "",
                  :hoja                   => 0,
                  :imprimir_hasta_hoja    => 0
                  })

  @recibo_sueldos = liquidacion_actual.recibo_sueldos.all
  if !@recibo_sueldos.any?
    flash[:error] = "No existen Movimientos para Listar"
    return
  end

  pdf = Prawn::Document.new(:left_margin => 35, :top_margin => 35,:page_size   => "LETTER",
#                              :background => img,
                            :page_layout => :portrait)
  offset = 0
    pdf.draw_text "Planilla de Remuneraciones".center(100), :at => [5,745],:style => :bold, :size => 10


  logo_id = AssociatedDocumentType.where(:document_type => "L").first.id
  con_logo = false

  if @recibo_sueldos.first.employee.consortium_id.to_i > 0

    if !logo_id.nil? && !Rails.env.development?
#      attach = @recibo_sueldos.first.employee.consortium.attachments.unscoped.where(:associated_document_type_id => logo_id).first()
#      con_logo = true

    end
    empresa.empresa             = @recibo_sueldos.first.employee.consortium.razon_social
    empresa.domicilio           = @recibo_sueldos.first.employee.consortium.calle + ' ' +
                                  @recibo_sueldos.first.employee.consortium.altura
    empresa.domicilio2          = @recibo_sueldos.first.employee.consortium.codigo_postal+' '+
                                  @recibo_sueldos.first.employee.consortium.location.detalle+' ('+
                                  @recibo_sueldos.first.employee.consortium.province.detalle+")"
    empresa.cuit                = @recibo_sueldos.first.employee.consortium.cuit
    empresa.inscripcion         = @recibo_sueldos.first.employee.consortium.numero_inscripcion
    empresa.caja                = @recibo_sueldos.first.employee.consortium.caja
    empresa.hoja                = @recibo_sueldos.first.employee.consortium.ultima_hoja_libro.to_i
    empresa.imprimir_hasta_hoja = @recibo_sueldos.first.employee.consortium.imprimir_hasta_hoja_libro.to_i
  else
    if !logo_id.nil?
#     attach = current_company.attachments.unscoped.where(:associated_document_type_id => logo_id).first
#     con_logo = true

    end
    empresa.empresa             = current_company.razon_social
    empresa.domicilio           = current_company.calle + ' ' +
                                  current_company.altura
    empresa.domicilio2          = current_company.codigo_postal+' '+
                                  current_company.location.detalle+' ('+
                                  current_company.province.detalle+")"
    empresa.cuit                = current_company.cuit
    empresa.inscripcion         = current_company.numero_inscripcion
    empresa.caja                = current_company.caja
    empresa.hoja                = current_company.ultima_hoja_libro.to_i
    empresa.imprimir_hasta_hoja = current_company.imprimir_hasta_hoja_libro.to_i
  end
  if con_logo
    if attach.adjunto_content_type[0..4] = "image"
      file_logo= Rails.root.join('tmp',attach.adjunto_file_name)
      Dir.mkdir(file_logo.dirname) unless File.directory?(file_logo.dirname)

      open( file_logo, 'wb' ) { |file|
          file.write(attach.adjunto_file)
        }

      empresa.logo = file_logo.to_s
    end
  end
  pdf.repeat(:all, :dynamic => true) do
#    pdf.image empresa.logo, :at => [5,750], :width => 30
    pdf.draw_text "Planilla de Remuneraciones".center(100), :at => [5,745],:style => :bold, :size => 10
    pdf.draw_text empresa.empresa.center(200), :at => [100,745],:style => :bold, :size => 10
    pdf.draw_text "Periodo de Liquidacion: " + @liquidacion.periodo.strftime("%m/%Y"), :at => [40, 725]
    pdf.draw_text "Hoja Nro.: " + pdf.page_number.to_s.rjust(4,"0"), :at => [410, 725]
  end
  data = [["Legajo","N o m b r e","Categoria", "Remuneraciones Con Descuento", "Remuneraciones Sin Descuento","Retenciones","Total Recibo"],
       [] ]
  thaber_con_descuento = 0
  thaber_sin_descuento = 0
  tretencion = 0
  @recibo_sueldos.each do |r|
     retencion = r.total_retenciones
     haber_total = r.total_haberes
     haber_con_descuento = r.total_haberes_con_descuento
     haber_sin_descuento = haber_total - r.total_haberes_con_descuento

     # haber = ReciboSueldo.joins(:detalle_recibo_habers).where(:id => r.id).sum(:total)
     tretencion = tretencion + retencion

app/helpers/liquidacions_helper.rb
module LiquidacionsHelper

  def liquidacion_links(liquidacion)
      links = []
      links << link_to_unless_current('Visualizar', liquidacion)
      links << link_to('Editar', edit_liquidacion_path(liquidacion))
      links << link_to('Borrar', liquidacion, :confirm => 'Esta Seguro?', :method => :delete)

      links.compact.join( " | ").html_safe

  end
end

app/views/liquidacions/_form.html.haml
= form_for(@liquidacion) do |f|
  = render 'shared/errorhandler', :obj_errors => @liquidacion.errors
  .clear
  %br/
  .form_box
    %table.tableForm
      %tr
        %td.columnLabel
          = f.label :periodo, :class => "apsLabel"
        %td.columnData
          /= f.text_field :periodo, :class => "apsDatetime" if @liquidacion.new_record?
          = f.date_select :periodo, :discard_day => true if @liquidacion.new_record?
          = @liquidacion.periodo unless @liquidacion.new_record?
      %tr
        %td.columnLabel
          = f.label :quincena, :class => "apsLabel"
        %td.columnData
          = f.text_field :quincena, :class => "apsTextbox" if @liquidacion.new_record?
          = @liquidacion.quincena unless @liquidacion.new_record?
      %tr
        %td.columnLabel
          = f.label :tipo_recibo_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :tipo_recibo_id, TipoRecibo.all, :id, :detalle, {:class => "apsSelect"} if @liquidacion.new_record?
          = @liquidacion.tipo_recibo.try(:detalle) unless @liquidacion.new_record?
      %tr
        %td.columnLabel
          = f.label :fecha_liquidacion, :class => "apsLabel"
        %td.columnData
          = f.text_field :fecha_liquidacion, :value => @liquidacion.fecha_liquidacion.to_s, :class => "apsDatetime"
      %tr
        %td.columnLabel
          = f.label :periodo_deposito, :class => "apsLabel"
        %td.columnData
          /= f.text_field :periodo_deposito, :class => "apsDatetime"
          = f.date_select :periodo_deposito, :discard_day => true
      %tr
        %td.columnLabel
          = f.label :fecha_deposito, :class => "apsLabel"
        %td.columnData
          = f.text_field :fecha_deposito, :value => @liquidacion.fecha_deposito.to_s, :class => "apsDatetime"
      %tr
        %td.columnLabel
          = f.label :bank_deposit_id, :class => "apsLabel"
        %td.columnData
          = f.collection_select :bank_deposit_id, BankDeposit.all, :id, :detalle, {:class => "apsSelect"}
      %tr
        %td.columnLabel
          = f.label :techo_retenciones, :class => "apsLabel"
        %td.columnData
          = f.text_field :techo_retenciones, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :fecha_cierre, :class => "apsLabel"
        %td.columnData
          = f.text_field :fecha_cierre, :value => @liquidacion.fecha_cierre.to_s, :class => "apsDatetime"
  .actions
    = f.submit :class => "btn success"

app/views/liquidacions/control_by_company.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Liquidacion.model_name.human, liquidacions_path
    - breadcrumb.item "Control de Liquidaciones", liquidacions_control_by_company_list_path
    - breadcrumb.item @liquidacion.periodo.strftime("%Y/%m"), nil, :active => true

.clear
.clear

/- if @liquidacion.recibo_sueldos.any?
- if true
  %table#recibo_sueldos.tableStandard
    %tr
      %th Legajo
      %th Empleado
      %th Total haberes
      %th Total retenciones
      %th Control

    - @liquidacion.recibo_sueldos.order("id").each do |item|
      %tr{:style => "background-color:" + (item.approved_date.blank? ? "#fff" : "#bbffb6")}
        %td= item.employee.legajo
        %td= item.employee.full_name
        /%td= item.id.to_s
        %td= item.total_haberes
        %td= item.total_retenciones.to_s
        %td= link_to 'Controlar', control_by_company_liquidacion_recibo_sueldo_path(@liquidacion, item), :rel => "twypsy", :title => t('scaffold.actions.show').titlecase

app/views/liquidacions/control_by_company_list.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Liquidacion.model_name.human, liquidacions_path
    - breadcrumb.item "Control de Liquidaciones", nil, :active => true

.clear
.clear

- if @liquidacions.any?
  /%h2 Liquidaciones disponibles
  %table#by_company.tableStandard
    %tr
      %th Periodo
      %th Quincena
      %th Tipo Recibo
      %th Control
      //%th Control total

    - @liquidacions.each do |liquidacion|
      %tr
        %td= liquidacion.periodo.strftime("%Y/%m")
        %td{:style => "text-align:center"}= liquidacion.quincena
        %td= liquidacion.tipo_recibo.try(:detalle)
        %td= link_to 'Controlar', control_by_company_liquidacion_path(liquidacion), :rel => "twypsy", :title => "Controlar"

app/views/liquidacions/edit.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Liquidacion.model_name.human, liquidacions_path
    - breadcrumb.item "#{@liquidacion.periodo.strftime('%m/%Y')}",nil, :active => true

= link_to t('scaffold.actions.show').titlecase, liquidacion_path(@liquidacion), :class => "btn info"
= link_to 'Carga Novedades', liquidacion_recibo_sueldos_path(@liquidacion), :class => "btn standad"
.clear
%br/
= render 'form'

app/views/liquidacions/index.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Liquidacion.model_name.human, liquidacions_path, :active => true
.clear
- if true
  = link_to t('scaffold.actions.new', :item => Liquidacion.model_name.human).titlecase , new_liquidacion_path(@liquidacion), :class => "btn success"
  - if @liquidacions.any?
    = link_to t('scaffold.actions.export').titlecase, liquidacions_path( :format => 'pdf'), :class => "btn info"
.clear
%br
/%h1 Listing liquidacions
- if @liquidacions.any?
  %table.tableStandard
    %tr
      %th Periodo
      %th Quincena
      %th Tipo Recibo
      %th Fecha liquidacion
      %th Banco ultimo deposito
      %th Periodo deposito
      %th Fecha deposito
      %th Fecha cierre
      %th Techo retenciones
      %th.last

    - @liquidacions.each do |item|
      %tr
        %td= item.periodo.strftime("%Y/%m")
        %td{:style => "text-align:center"}= item.quincena
        %td= item.tipo_recibo.try(:detalle)
        %td{:style => "text-align:center"}= item.fecha_liquidacion.strftime("%d/%m/%Y")
        %td= item.bank_deposit.try(:detalle)
        %td= (item.periodo_deposito.blank? ? '  /  ' :item.periodo_deposito.strftime("%Y/%m"))
        %td= item.fecha_deposito.strftime("%d/%m/%Y")
        %td= (item.fecha_cierre.blank? ? '  /  /' : item.fecha_cierre.strftime("%d/%m/%Y"))
        %td= item.techo_retenciones
        -#%td= liquidacion_links(liquidacion)
        %td.last.actions
          = link_to icon('application_get', :small, :title => t('scaffold.actions.show').titlecase), item, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_edit', :small, :title => t('scaffold.actions.edit').titlecase), edit_liquidacion_path(item), :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_delete', :small, :title => t('scaffold.actions.destroy').titlecase), item, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
    .clear
    /.block{:style => 'margin:20px;'}= paginate(@bank_deposits)
  .clear
.clear

app/views/liquidacions/new.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Liquidacion.model_name.human, liquidacions_path
    - breadcrumb.item t('scaffold.actions.new', :item => Liquidacion.model_name.human).titlecase , nil, :active => true

= render 'form'

app/views/liquidacions/show.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Liquidacion.model_name.human, liquidacions_path
    - breadcrumb.item "#{@liquidacion.periodo.strftime('%m/%Y')}",nil, :active => true

= link_to t('scaffold.actions.edit').titlecase, edit_liquidacion_path(@liquidacion), :class => "btn success" |
= link_to t('scaffold.actions.destroy').titlecase, @liquidacion, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :class => "btn danger"
= link_to 'Libro Sueldos', liquidacion_path(@liquidacion, :format => 'pdf'), :class => "btn standard"
= link_to 'Planilla de Remuneraciones', liquidacion_path(@liquidacion, :format => 'json'), :class => "btn standard"
= link_to 'Interfase Sicoss', liquidacion_path(@liquidacion, :format => 'text'), :class => "btn standard"
= link_to 'Prueba', liquidacion_path(@liquidacion, :format => 'xml'), :class => "btn standard"
.clear
%br/
/%h1 Visualizacion de Liquidacion
/%p#notice= notice
= form_for(@liquidacion) do |f|
  - if @liquidacion.errors.any?
    #error_explanation
      %h2
        = pluralize(@liquidacion.errors.count, "error")
        prohibited this bank_deposit from being saved:
      %ul
        - @liquidacion.errors.full_messages.each do |msg|
          %li= msg
  %table.tableForm
    %tr
      %td.columnLabel
        = f.label :periodo, :class => "apsLabel"
      %td.columnData
        = @liquidacion.periodo.month
    %tr
      %td.columnLabel
        = f.label :tipo_recibo, :class => "apsLabel"
      %td.columnData
        = @liquidacion.tipo_recibo.try(:detalle)
    %tr
      %td.columnLabel
        = f.label :quincena, :class => "apsLabel"
      %td.columnData
        = @liquidacion.quincena
    %tr
      %td.columnLabel
        = f.label :fecha_liquidacion, :class => "apsLabel"
      %td.columnData
        = @liquidacion.fecha_liquidacion
    %tr
      %td.columnLabel
        = f.label :bank_deposit, :class => "apsLabel"
      %td.columnData
        = @liquidacion.bank_deposit.try(:detalle)
    %tr
      %td.columnLabel
        = f.label :periodo_deposito, :class => "apsLabel"
      %td.columnData
        = @liquidacion.periodo_deposito.month
    %tr
      %td.columnLabel
        = f.label :fecha_deposito, :class => "apsLabel"
      %td.columnData
        = @liquidacion.fecha_deposito
    %tr
      %td.columnLabel
        = f.label :fecha_cierre, :class => "apsLabel"
      %td.columnData
        = @liquidacion.fecha_cierre
    %tr
      %td.columnLabel
        = f.label :techo_retenciones, :class => "apsLabel"
      %td.columnData
        = @liquidacion.techo_retenciones
.clear