config/routes.rb
APSSueldos::Application.routes.draw do |map|

  resources :companies

  resources :consortia

  resources :numeradors

  devise_for :users do
    get '/login' => 'devise/sessions#new', :as => :login
    get '/logout' => 'devise/sessions#destroy', :as => :logout
  end

  resources :users

  resources :sicoss_format_employers

  resources :sicoss_formats

  resources :sicoss_regimen_types

  resources :sicoss_reduction_zones

  resources :sicoss_locations

  resources :sicoss_damageds

  resources :sicoss_contract_modes

  resources :sicoss_activities

  resources :sicoss_conditions

  resources :sicoss_situations

  resources :sicoss_employer_types

  resources :siscoss_regimen_types

  resources :siscoss_regimen

  resources :siscoss_reduction_zones

  resources :siscoss_locations

  resources :siscoss_contract_modes

  resources :siscoss_activities

  resources :siscoss_conditions

  resources :siscoss_situations

  resources :siscoss_employer_types

  resources :syscoss_regimen_types

  resources :syscoss_regimen

  resources :syscoss_reduction_zones

  resources :syscoss_locations

  resources :syscoss_damageds

  resources :syscoss_contract_modes

  resources :syscoss_activities

  resources :syscoss_conditions

  resources :syscoss_situations

  resources :syscoss_employer_types

  resources :employer_types

  resources :activities

  resources :kinships

  resources :associated_document_types

  resources :EmployeeDocumentsController

  map.resources :attachments    , :only => :show

  resources :causa_egresos

  resources :email_types

  resources :employees do
    resources :employee_familiars
    resources :employee_retention_concepts
    resources :employee_remunerative_concepts
  end
  resources :deduccion_ganancias_tables

  resources :tipo_recibos

  resources :categories do
    member do
      get "imprimir", :action => :print
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  match '/print_table' => 'application#print_table', :via => :get
  match 'liquidacions/control_by_company_list' => 'liquidacions#control_by_company_list', :via => :get
  resources :liquidacions do
    member do
       get "control_by_company", :action => :control_by_company
    end
    resources :recibo_sueldos do
      member do
        get "control_by_company", :action => :control_by_company
        get "update_approved_fields", :action => :update_approved_fields
        get "update_disapproved_fields", :action => :update_disapproved_fields
      end
      resources :detalle_recibo_retencions
      resources :detalle_recibo_habers
      member do
        get "calculo_recibo", :action => :calculo_recibo
      end
    end
  end

  resources :data_to_asks

  resources :group_remunerations

  resources :employer_contribution_concepts

  resources :retention_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :remunerative_concepts do
    member do
      get "notify_changes", :action => :notify_changes
      get "calculate_changes", :action => :calculate_changes
    end
  end

  resources :activities, :path => 'Actividades'

  resources :insurance_beneficiaries

  resources :bank_deposits

  resources :educational_levels

  resources :group_employer_contributions

  resources :bank_deposit_account_types

  resources :insurance_companies

  resources :employments

  resources :accounting_imputations

  resources :contract_modes

  resources :home_abouts

  resources :cost_centers

  resources :group_retentions

  resources :remuneration_types

  resources :labor_unions

  resources :health_insurances

  resources :places

  resources :tasks

  resources :sections

  resources :character_services

  resources :countries

  resources :provinces

  resources :locations

  resources :marital_statuses

  resources :nationalities

  resources :issueds

  resources :document_types

  resources :menus
  resources :menu_roles
  resources :menu_users
  resources :user_authorizations
  resources :user_roles

  root :to => "liquidacions#index"
  

end

app/views/authorizations/_form.html.haml
= form_for(@authorization) do |f|
  = render 'shared/errorhandler', :obj_errors => @authorization.errors
  .clear
  .form_box
    .form_box_title
    /  %span.title= Authorization.model_name.human
    %table.tableForm
      %tr
        %td.columnLabel
          = f.label :code, :class => "apsLabel"
        %td.columnData
          = f.text_field :code, :class => "apsTextbox"
      %tr
        %td.columnLabel
          = f.label :name, :class => "apsLabel"
        %td.columnData
          = f.text_field :name, :class => "apsTextbox"
  .actions
    = f.submit :class => "btn success"

app/views/authorizations/edit.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Authorization.model_name.human, authorizations_path 
    - breadcrumb.item "#{@authorization.name.titlecase}", authorization_path(@authorization), :active => true

= link_to t('scaffold.actions.show').titlecase, authorization_path(@authorization), :class => "btn info" 
.clear
%br/
= render 'form'

app/views/authorizations/index.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Authorization.model_name.human, authorizations_path, :active => true
.clear
- if true
  = link_to t('scaffold.actions.new', :item => Authorization.model_name.human) , new_authorization_path(@authorization), :class => "btn success" 
  - if @authorizations.any?
    = link_to t('scaffold.actions.export').titlecase, "/print_table?tablename=" + Authorization.model_name, :class => "btn info"

- if @authorizations.any?
  %table.tableStandard
    %tr
      %th= sort_link @search, :code, @authorizations.human_attribute_name('code')
      %th= sort_link @search, :name, @authorizations.human_attribute_name('name')
      %th.last

    - @authorizations.each do |item|
      %tr
        %td= item.code
        %td= item.name
        %td.last.actions
          = link_to icon('application_get', :small, :title => t('scaffold.actions.show').titlecase), item, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_edit', :small, :title => t('scaffold.actions.edit').titlecase), edit_authorization_path(item), :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
          = link_to icon('application_delete', :small, :title => t('scaffold.actions.destroy').titlecase), item, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :rel => "twypsy", :title => t('scaffold.actions.show').titlecase
    .clear
    .block{:style => 'margin:20px;'}= paginate(@authorizations)
  .clear
.clear

app/views/authorizations/new.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Authorization.model_name.human, authorizations_path
    - breadcrumb.item t('scaffold.actions.new', :item => Authorization.model_name.human).titlecase , nil, :active => true

= render 'form'

app/views/authorizations/show.html.haml
- content_for(:breadcrumbs) do
  = breadcrumbs do |breadcrumb|
    - breadcrumb.item current_company.name.titlecase, root_path
    - breadcrumb.item Authorization.model_name.human, authorizations_path 
    - breadcrumb.item "#{@authorization.name.titlecase}", nil, :active => true

= link_to t('scaffold.actions.edit').titlecase, edit_authorization_path(@authorization), :class => "btn success" |
= link_to t('scaffold.actions.destroy').titlecase, @authorization, :confirm => t('scaffold.actions.destroy_confirm'), :method => :delete, :class => "btn danger"
.clear
%br/
= form_for(@authorization) do |f|
  = render 'shared/errorhandler', :obj_errors => @authorization.errors
  .form_box
    %table.tableForm
      %tr
        %td.columnLabel
          = f.label :code, :class => "apsLabel"
        %td.columnData
          = @authorization.code
      %tr
        %td.columnLabel
          = f.label :name, :class => "apsLabel"
        %td.columnData
          = @authorization.name
.clear